package com.cosmetics.cosmeticspos.domain;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Category.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Category implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** categoryId. */
	private Integer categoryid;

	/** name. */
	private String name;

	/** The set of Product. */
	private Set<Product> productSet;

	/**
	 * Constructor.
	 */
	public Category() {
		this.productSet = new HashSet<Product>();
	}

	/**
	 * Set the categoryId.
	 * 
	 * @param categoryid
	 *            categoryId
	 */
	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	/**
	 * Get the categoryId.
	 * 
	 * @return categoryId
	 */
	public Integer getCategoryid() {
		return this.categoryid;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the set of the Product.
	 * 
	 * @param productSet
	 *            The set of Product
	 */
	public void setProductSet(Set<Product> productSet) {
		this.productSet = productSet;
	}

	/**
	 * Add the Product.
	 * 
	 * @param product
	 *            Product
	 */
	public void addProduct(Product product) {
		this.productSet.add(product);
	}

	/**
	 * Get the set of the Product.
	 * 
	 * @return The set of Product
	 */
	public Set<Product> getProductSet() {
		return this.productSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((categoryid == null) ? 0 : categoryid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Category other = (Category) obj;
		if (categoryid == null) {
			if (other.categoryid != null) {
				return false;
			}
		} else if (!categoryid.equals(other.categoryid)) {
			return false;
		}
		return true;
	}

}
