package com.cosmetics.cosmeticspos.domain;

import java.io.Serializable;

/**
 * Model class of ItemTransaction.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Itemtransaction implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** itemTransactionId. */
	private Integer itemtransactionid;

	/** Product. */
	private Product product;

	/** Sale. */
	private Sale sale;

	/** qty. */
	private Integer qty;

	/** unitPrice. */
	private Integer unitprice;

	/** amount. */
	private Integer amount;

	/** discount. */
	private Integer discount;

	/** balance. */
	private Integer balance;

	/**
	 * Constructor.
	 */
	public Itemtransaction() {
	}

	/**
	 * Set the itemTransactionId.
	 * 
	 * @param itemtransactionid
	 *            itemTransactionId
	 */
	public void setItemtransactionid(Integer itemtransactionid) {
		this.itemtransactionid = itemtransactionid;
	}

	/**
	 * Get the itemTransactionId.
	 * 
	 * @return itemTransactionId
	 */
	public Integer getItemtransactionid() {
		return this.itemtransactionid;
	}

	/**
	 * Set the Product.
	 * 
	 * @param product
	 *            Product
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * Get the Product.
	 * 
	 * @return Product
	 */
	public Product getProduct() {
		return this.product;
	}

	/**
	 * Set the Sale.
	 * 
	 * @param sale
	 *            Sale
	 */
	public void setSale(Sale sale) {
		this.sale = sale;
	}

	/**
	 * Get the Sale.
	 * 
	 * @return Sale
	 */
	public Sale getSale() {
		return this.sale;
	}

	/**
	 * Set the qty.
	 * 
	 * @param qty
	 *            qty
	 */
	public void setQty(Integer qty) {
		this.qty = qty;
	}

	/**
	 * Get the qty.
	 * 
	 * @return qty
	 */
	public Integer getQty() {
		return this.qty;
	}

	/**
	 * Set the unitPrice.
	 * 
	 * @param unitprice
	 *            unitPrice
	 */
	public void setUnitprice(Integer unitprice) {
		this.unitprice = unitprice;
	}

	/**
	 * Get the unitPrice.
	 * 
	 * @return unitPrice
	 */
	public Integer getUnitprice() {
		return this.unitprice;
	}

	/**
	 * Set the amount.
	 * 
	 * @param amount
	 *            amount
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/**
	 * Get the amount.
	 * 
	 * @return amount
	 */
	public Integer getAmount() {
		return this.amount;
	}

	/**
	 * Set the discount.
	 * 
	 * @param discount
	 *            discount
	 */
	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	/**
	 * Get the discount.
	 * 
	 * @return discount
	 */
	public Integer getDiscount() {
		return this.discount;
	}

	/**
	 * Set the balance.
	 * 
	 * @param balance
	 *            balance
	 */
	public void setBalance(Integer balance) {
		this.balance = balance;
	}

	/**
	 * Get the balance.
	 * 
	 * @return balance
	 */
	public Integer getBalance() {
		return this.balance;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemtransactionid == null) ? 0 : itemtransactionid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Itemtransaction other = (Itemtransaction) obj;
		if (itemtransactionid == null) {
			if (other.itemtransactionid != null) {
				return false;
			}
		} else if (!itemtransactionid.equals(other.itemtransactionid)) {
			return false;
		}
		return true;
	}

}
