package com.cosmetics.cosmeticspos.domain;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Product.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Product implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** productId. */
	private Integer productid;

	/** UserAccount. */
	private int userAccountId;

	/** Category. */
	private Category category;

	/** type. */
	private Integer type;

	/** photoOne. */
	private String photoone;

	/** photoTwo. */
	private String phototwo;

	/** photoThree. */
	private String photothree;

	/** photoFour. */
	private String photofour;

	/** colorOne. */
	private String colorone;

	/** colorTwo. */
	private String colortwo;

	/** colorThree. */
	private String colorthree;

	/** colorFour. */
	private String colorfour;

	/** priceOne. */
	private Integer priceone;

	/** priceTwo. */
	private Integer pricetwo;

	/** sizeOne. */
	private Integer sizeone;

	/** sizeTwo. */
	private Integer sizetwo;

	/** title. */
	private String title;

	/** detail. */
	private String detail;

	/** code. */
	private String code;

	/** count. */
	private Integer count;

	/** discountPriceOne. */
	private Integer discountpriceone;

	/** discountPriceTwo. */
	private Integer discountpricetwo;

	/** percent. */
	private Integer percent;

	/** normalPriceOne. */
	private Integer normalpriceone;

	/** normalPriceTwo. */
	private Integer normalpricetwo;

	/** The set of ItemTransaction. */
	private Set<Itemtransaction> itemtransactionSet;

	/** The set of Rating. */
	private Set<Rating> ratingSet;

	/**
	 * Constructor.
	 */
	public Product() {
		this.itemtransactionSet = new HashSet<Itemtransaction>();
		this.ratingSet = new HashSet<Rating>();
	}

	/**
	 * Set the productId.
	 * 
	 * @param productid
	 *            productId
	 */
	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	/**
	 * Get the productId.
	 * 
	 * @return productId
	 */
	public Integer getProductid() {
		return this.productid;
	}

	/**
	 * Set the UserAccount.
	 * 
	 * @param useraccount
	 *            UserAccount
	 */
	public void setUseraccount(Useraccount useraccount) {
		this.useraccount = useraccount;
	}

	/**
	 * Get the UserAccount.
	 * 
	 * @return UserAccount
	 */
	public Useraccount getUseraccount() {
		return this.useraccount;
	}

	/**
	 * Set the Category.
	 * 
	 * @param category
	 *            Category
	 */
	public void setCategory(Category category) {
		this.category = category;
	}

	/**
	 * Get the Category.
	 * 
	 * @return Category
	 */
	public Category getCategory() {
		return this.category;
	}

	/**
	 * Set the type.
	 * 
	 * @param type
	 *            type
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * Get the type.
	 * 
	 * @return type
	 */
	public Integer getType() {
		return this.type;
	}

	/**
	 * Set the photoOne.
	 * 
	 * @param photoone
	 *            photoOne
	 */
	public void setPhotoone(String photoone) {
		this.photoone = photoone;
	}

	/**
	 * Get the photoOne.
	 * 
	 * @return photoOne
	 */
	public String getPhotoone() {
		return this.photoone;
	}

	/**
	 * Set the photoTwo.
	 * 
	 * @param phototwo
	 *            photoTwo
	 */
	public void setPhototwo(String phototwo) {
		this.phototwo = phototwo;
	}

	/**
	 * Get the photoTwo.
	 * 
	 * @return photoTwo
	 */
	public String getPhototwo() {
		return this.phototwo;
	}

	/**
	 * Set the photoThree.
	 * 
	 * @param photothree
	 *            photoThree
	 */
	public void setPhotothree(String photothree) {
		this.photothree = photothree;
	}

	/**
	 * Get the photoThree.
	 * 
	 * @return photoThree
	 */
	public String getPhotothree() {
		return this.photothree;
	}

	/**
	 * Set the photoFour.
	 * 
	 * @param photofour
	 *            photoFour
	 */
	public void setPhotofour(String photofour) {
		this.photofour = photofour;
	}

	/**
	 * Get the photoFour.
	 * 
	 * @return photoFour
	 */
	public String getPhotofour() {
		return this.photofour;
	}

	/**
	 * Set the colorOne.
	 * 
	 * @param colorone
	 *            colorOne
	 */
	public void setColorone(String colorone) {
		this.colorone = colorone;
	}

	/**
	 * Get the colorOne.
	 * 
	 * @return colorOne
	 */
	public String getColorone() {
		return this.colorone;
	}

	/**
	 * Set the colorTwo.
	 * 
	 * @param colortwo
	 *            colorTwo
	 */
	public void setColortwo(String colortwo) {
		this.colortwo = colortwo;
	}

	/**
	 * Get the colorTwo.
	 * 
	 * @return colorTwo
	 */
	public String getColortwo() {
		return this.colortwo;
	}

	/**
	 * Set the colorThree.
	 * 
	 * @param colorthree
	 *            colorThree
	 */
	public void setColorthree(String colorthree) {
		this.colorthree = colorthree;
	}

	/**
	 * Get the colorThree.
	 * 
	 * @return colorThree
	 */
	public String getColorthree() {
		return this.colorthree;
	}

	/**
	 * Set the colorFour.
	 * 
	 * @param colorfour
	 *            colorFour
	 */
	public void setColorfour(String colorfour) {
		this.colorfour = colorfour;
	}

	/**
	 * Get the colorFour.
	 * 
	 * @return colorFour
	 */
	public String getColorfour() {
		return this.colorfour;
	}

	/**
	 * Set the priceOne.
	 * 
	 * @param priceone
	 *            priceOne
	 */
	public void setPriceone(Integer priceone) {
		this.priceone = priceone;
	}

	/**
	 * Get the priceOne.
	 * 
	 * @return priceOne
	 */
	public Integer getPriceone() {
		return this.priceone;
	}

	/**
	 * Set the priceTwo.
	 * 
	 * @param pricetwo
	 *            priceTwo
	 */
	public void setPricetwo(Integer pricetwo) {
		this.pricetwo = pricetwo;
	}

	/**
	 * Get the priceTwo.
	 * 
	 * @return priceTwo
	 */
	public Integer getPricetwo() {
		return this.pricetwo;
	}

	/**
	 * Set the sizeOne.
	 * 
	 * @param sizeone
	 *            sizeOne
	 */
	public void setSizeone(Integer sizeone) {
		this.sizeone = sizeone;
	}

	/**
	 * Get the sizeOne.
	 * 
	 * @return sizeOne
	 */
	public Integer getSizeone() {
		return this.sizeone;
	}

	/**
	 * Set the sizeTwo.
	 * 
	 * @param sizetwo
	 *            sizeTwo
	 */
	public void setSizetwo(Integer sizetwo) {
		this.sizetwo = sizetwo;
	}

	/**
	 * Get the sizeTwo.
	 * 
	 * @return sizeTwo
	 */
	public Integer getSizetwo() {
		return this.sizetwo;
	}

	/**
	 * Set the title.
	 * 
	 * @param title
	 *            title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Get the title.
	 * 
	 * @return title
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * Set the detail.
	 * 
	 * @param detail
	 *            detail
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * Get the detail.
	 * 
	 * @return detail
	 */
	public String getDetail() {
		return this.detail;
	}

	/**
	 * Set the code.
	 * 
	 * @param code
	 *            code
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * Get the code.
	 * 
	 * @return code
	 */
	public String getCode() {
		return this.code;
	}

	/**
	 * Set the count.
	 * 
	 * @param count
	 *            count
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * Get the count.
	 * 
	 * @return count
	 */
	public Integer getCount() {
		return this.count;
	}

	/**
	 * Set the discountPriceOne.
	 * 
	 * @param discountpriceone
	 *            discountPriceOne
	 */
	public void setDiscountpriceone(Integer discountpriceone) {
		this.discountpriceone = discountpriceone;
	}

	/**
	 * Get the discountPriceOne.
	 * 
	 * @return discountPriceOne
	 */
	public Integer getDiscountpriceone() {
		return this.discountpriceone;
	}

	/**
	 * Set the discountPriceTwo.
	 * 
	 * @param discountpricetwo
	 *            discountPriceTwo
	 */
	public void setDiscountpricetwo(Integer discountpricetwo) {
		this.discountpricetwo = discountpricetwo;
	}

	/**
	 * Get the discountPriceTwo.
	 * 
	 * @return discountPriceTwo
	 */
	public Integer getDiscountpricetwo() {
		return this.discountpricetwo;
	}

	/**
	 * Set the percent.
	 * 
	 * @param percent
	 *            percent
	 */
	public void setPercent(Integer percent) {
		this.percent = percent;
	}

	/**
	 * Get the percent.
	 * 
	 * @return percent
	 */
	public Integer getPercent() {
		return this.percent;
	}

	/**
	 * Set the normalPriceOne.
	 * 
	 * @param normalpriceone
	 *            normalPriceOne
	 */
	public void setNormalpriceone(Integer normalpriceone) {
		this.normalpriceone = normalpriceone;
	}

	/**
	 * Get the normalPriceOne.
	 * 
	 * @return normalPriceOne
	 */
	public Integer getNormalpriceone() {
		return this.normalpriceone;
	}

	/**
	 * Set the normalPriceTwo.
	 * 
	 * @param normalpricetwo
	 *            normalPriceTwo
	 */
	public void setNormalpricetwo(Integer normalpricetwo) {
		this.normalpricetwo = normalpricetwo;
	}

	/**
	 * Get the normalPriceTwo.
	 * 
	 * @return normalPriceTwo
	 */
	public Integer getNormalpricetwo() {
		return this.normalpricetwo;
	}

	/**
	 * Set the set of the ItemTransaction.
	 * 
	 * @param itemtransactionSet
	 *            The set of ItemTransaction
	 */
	public void setItemtransactionSet(Set<Itemtransaction> itemtransactionSet) {
		this.itemtransactionSet = itemtransactionSet;
	}

	/**
	 * Add the ItemTransaction.
	 * 
	 * @param itemtransaction
	 *            ItemTransaction
	 */
	public void addItemtransaction(Itemtransaction itemtransaction) {
		this.itemtransactionSet.add(itemtransaction);
	}

	/**
	 * Get the set of the ItemTransaction.
	 * 
	 * @return The set of ItemTransaction
	 */
	public Set<Itemtransaction> getItemtransactionSet() {
		return this.itemtransactionSet;
	}

	/**
	 * Set the set of the Rating.
	 * 
	 * @param ratingSet
	 *            The set of Rating
	 */
	public void setRatingSet(Set<Rating> ratingSet) {
		this.ratingSet = ratingSet;
	}

	/**
	 * Add the Rating.
	 * 
	 * @param rating
	 *            Rating
	 */
	public void addRating(Rating rating) {
		this.ratingSet.add(rating);
	}

	/**
	 * Get the set of the Rating.
	 * 
	 * @return The set of Rating
	 */
	public Set<Rating> getRatingSet() {
		return this.ratingSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((productid == null) ? 0 : productid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Product other = (Product) obj;
		if (productid == null) {
			if (other.productid != null) {
				return false;
			}
		} else if (!productid.equals(other.productid)) {
			return false;
		}
		return true;
	}

}
