package com.cosmetics.cosmeticspos.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of Rating.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Rating implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ratingId. */
	private Integer ratingid;

	/** UserAccount. */
	private Useraccount customeriduseraccount;

	/** Product. */
	private Product product;

	/** rating. */
	private Integer rating;

	/** date. */
	private Date date;

	/**
	 * Constructor.
	 */
	public Rating() {
	}

	/**
	 * Set the ratingId.
	 * 
	 * @param ratingid
	 *            ratingId
	 */
	public void setRatingid(Integer ratingid) {
		this.ratingid = ratingid;
	}

	/**
	 * Get the ratingId.
	 * 
	 * @return ratingId
	 */
	public Integer getRatingid() {
		return this.ratingid;
	}

	/**
	 * Set the UserAccount.
	 * 
	 * @param customeriduseraccount
	 *            UserAccount
	 */
	public void setCustomeriduseraccount(Useraccount customeriduseraccount) {
		this.customeriduseraccount = customeriduseraccount;
	}

	/**
	 * Get the UserAccount.
	 * 
	 * @return UserAccount
	 */
	public Useraccount getCustomeriduseraccount() {
		return this.customeriduseraccount;
	}

	/**
	 * Set the Product.
	 * 
	 * @param product
	 *            Product
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * Get the Product.
	 * 
	 * @return Product
	 */
	public Product getProduct() {
		return this.product;
	}

	/**
	 * Set the rating.
	 * 
	 * @param rating
	 *            rating
	 */
	public void setRating(Integer rating) {
		this.rating = rating;
	}

	/**
	 * Get the rating.
	 * 
	 * @return rating
	 */
	public Integer getRating() {
		return this.rating;
	}

	/**
	 * Set the date.
	 * 
	 * @param date
	 *            date
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * Get the date.
	 * 
	 * @return date
	 */
	public Date getDate() {
		return this.date;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ratingid == null) ? 0 : ratingid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Rating other = (Rating) obj;
		if (ratingid == null) {
			if (other.ratingid != null) {
				return false;
			}
		} else if (!ratingid.equals(other.ratingid)) {
			return false;
		}
		return true;
	}

}
