package com.cosmetics.cosmeticspos.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Sale.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Sale implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** saleId. */
	private Integer saleid;

	/** UserAccount. */
	private Useraccount customeriduseraccount;


	/** receivedDate. */
	private Date receiveddate;

	/** date. */
	private Date date;

	/** name. */
	private String name;

	/** phone. */
	private String phone;

	/** address. */
	private String address;

	/** The set of ItemTransaction. */
	private Set<Itemtransaction> itemtransactionSet;

	/** The set of Transaction. */
	private Set<Transaction> transactionSet;

	/**
	 * Constructor.
	 */
	public Sale() {
		this.itemtransactionSet = new HashSet<Itemtransaction>();
		this.transactionSet = new HashSet<Transaction>();
	}

	/**
	 * Set the saleId.
	 * 
	 * @param saleid
	 *            saleId
	 */
	public void setSaleid(Integer saleid) {
		this.saleid = saleid;
	}

	/**
	 * Get the saleId.
	 * 
	 * @return saleId
	 */
	public Integer getSaleid() {
		return this.saleid;
	}

	/**
	 * Set the UserAccount.
	 * 
	 * @param customeriduseraccount
	 *            UserAccount
	 */
	public void setCustomeriduseraccount(Useraccount customeriduseraccount) {
		this.customeriduseraccount = customeriduseraccount;
	}

	/**
	 * Get the UserAccount.
	 * 
	 * @return UserAccount
	 */
	public Useraccount getCustomeriduseraccount() {
		return this.customeriduseraccount;
	}

	/**
	 * Set the Township.
	 * 
	 * @param township
	 *            Township
	 */
	public void setTownship(Township township) {
		this.township = township;
	}

	/**
	 * Get the Township.
	 * 
	 * @return Township
	 */
	public Township getTownship() {
		return this.township;
	}

	/**
	 * Set the receivedDate.
	 * 
	 * @param receiveddate
	 *            receivedDate
	 */
	public void setReceiveddate(Date receiveddate) {
		this.receiveddate = receiveddate;
	}

	/**
	 * Get the receivedDate.
	 * 
	 * @return receivedDate
	 */
	public Date getReceiveddate() {
		return this.receiveddate;
	}

	/**
	 * Set the date.
	 * 
	 * @param date
	 *            date
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * Get the date.
	 * 
	 * @return date
	 */
	public Date getDate() {
		return this.date;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the phone.
	 * 
	 * @param phone
	 *            phone
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Get the phone.
	 * 
	 * @return phone
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * Set the address.
	 * 
	 * @param address
	 *            address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * Get the address.
	 * 
	 * @return address
	 */
	public String getAddress() {
		return this.address;
	}

	/**
	 * Set the set of the ItemTransaction.
	 * 
	 * @param itemtransactionSet
	 *            The set of ItemTransaction
	 */
	public void setItemtransactionSet(Set<Itemtransaction> itemtransactionSet) {
		this.itemtransactionSet = itemtransactionSet;
	}

	/**
	 * Add the ItemTransaction.
	 * 
	 * @param itemtransaction
	 *            ItemTransaction
	 */
	public void addItemtransaction(Itemtransaction itemtransaction) {
		this.itemtransactionSet.add(itemtransaction);
	}

	/**
	 * Get the set of the ItemTransaction.
	 * 
	 * @return The set of ItemTransaction
	 */
	public Set<Itemtransaction> getItemtransactionSet() {
		return this.itemtransactionSet;
	}

	/**
	 * Set the set of the Transaction.
	 * 
	 * @param transactionSet
	 *            The set of Transaction
	 */
	public void setTransactionSet(Set<Transaction> transactionSet) {
		this.transactionSet = transactionSet;
	}

	/**
	 * Add the Transaction.
	 * 
	 * @param transaction
	 *            Transaction
	 */
	public void addTransaction(Transaction transaction) {
		this.transactionSet.add(transaction);
	}

	/**
	 * Get the set of the Transaction.
	 * 
	 * @return The set of Transaction
	 */
	public Set<Transaction> getTransactionSet() {
		return this.transactionSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((saleid == null) ? 0 : saleid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Sale other = (Sale) obj;
		if (saleid == null) {
			if (other.saleid != null) {
				return false;
			}
		} else if (!saleid.equals(other.saleid)) {
			return false;
		}
		return true;
	}

}
