package com.cosmetics.cosmeticspos.domain;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Township.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Township implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** townshipId. */
	private Integer townshipid;

	/** City. */
	private City city;

	/** townshipName. */
	private Integer townshipname;

	/** The set of Sale. */
	private Set<Sale> saleSet;

	/**
	 * Constructor.
	 */
	public Township() {
		this.saleSet = new HashSet<Sale>();
	}

	/**
	 * Set the townshipId.
	 * 
	 * @param townshipid
	 *            townshipId
	 */
	public void setTownshipid(Integer townshipid) {
		this.townshipid = townshipid;
	}

	/**
	 * Get the townshipId.
	 * 
	 * @return townshipId
	 */
	public Integer getTownshipid() {
		return this.townshipid;
	}

	/**
	 * Set the City.
	 * 
	 * @param city
	 *            City
	 */
	public void setCity(City city) {
		this.city = city;
	}

	/**
	 * Get the City.
	 * 
	 * @return City
	 */
	public City getCity() {
		return this.city;
	}

	/**
	 * Set the townshipName.
	 * 
	 * @param townshipname
	 *            townshipName
	 */
	public void setTownshipname(Integer townshipname) {
		this.townshipname = townshipname;
	}

	/**
	 * Get the townshipName.
	 * 
	 * @return townshipName
	 */
	public Integer getTownshipname() {
		return this.townshipname;
	}

	/**
	 * Set the set of the Sale.
	 * 
	 * @param saleSet
	 *            The set of Sale
	 */
	public void setSaleSet(Set<Sale> saleSet) {
		this.saleSet = saleSet;
	}

	/**
	 * Add the Sale.
	 * 
	 * @param sale
	 *            Sale
	 */
	public void addSale(Sale sale) {
		this.saleSet.add(sale);
	}

	/**
	 * Get the set of the Sale.
	 * 
	 * @return The set of Sale
	 */
	public Set<Sale> getSaleSet() {
		return this.saleSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((townshipid == null) ? 0 : townshipid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Township other = (Township) obj;
		if (townshipid == null) {
			if (other.townshipid != null) {
				return false;
			}
		} else if (!townshipid.equals(other.townshipid)) {
			return false;
		}
		return true;
	}

}
