package com.cosmetics.cosmeticspos.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of Transaction.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Transaction implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** transactionId. */
	private Integer transactionid;

	/** Sale. */
	private Sale sale;

	/** payment. */
	private Integer payment;

	/** balance. */
	private Integer balance;

	/** paymentType. */
	private String paymenttype;

	/** date. */
	private Date date;

	/** modifiedDate. */
	private Date modifieddate;

	/**
	 * Constructor.
	 */
	public Transaction() {
	}

	/**
	 * Set the transactionId.
	 * 
	 * @param transactionid
	 *            transactionId
	 */
	public void setTransactionid(Integer transactionid) {
		this.transactionid = transactionid;
	}

	/**
	 * Get the transactionId.
	 * 
	 * @return transactionId
	 */
	public Integer getTransactionid() {
		return this.transactionid;
	}

	/**
	 * Set the Sale.
	 * 
	 * @param sale
	 *            Sale
	 */
	public void setSale(Sale sale) {
		this.sale = sale;
	}

	/**
	 * Get the Sale.
	 * 
	 * @return Sale
	 */
	public Sale getSale() {
		return this.sale;
	}

	/**
	 * Set the payment.
	 * 
	 * @param payment
	 *            payment
	 */
	public void setPayment(Integer payment) {
		this.payment = payment;
	}

	/**
	 * Get the payment.
	 * 
	 * @return payment
	 */
	public Integer getPayment() {
		return this.payment;
	}

	/**
	 * Set the balance.
	 * 
	 * @param balance
	 *            balance
	 */
	public void setBalance(Integer balance) {
		this.balance = balance;
	}

	/**
	 * Get the balance.
	 * 
	 * @return balance
	 */
	public Integer getBalance() {
		return this.balance;
	}

	/**
	 * Set the paymentType.
	 * 
	 * @param paymenttype
	 *            paymentType
	 */
	public void setPaymenttype(String paymenttype) {
		this.paymenttype = paymenttype;
	}

	/**
	 * Get the paymentType.
	 * 
	 * @return paymentType
	 */
	public String getPaymenttype() {
		return this.paymenttype;
	}

	/**
	 * Set the date.
	 * 
	 * @param date
	 *            date
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * Get the date.
	 * 
	 * @return date
	 */
	public Date getDate() {
		return this.date;
	}

	/**
	 * Set the modifiedDate.
	 * 
	 * @param modifieddate
	 *            modifiedDate
	 */
	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}

	/**
	 * Get the modifiedDate.
	 * 
	 * @return modifiedDate
	 */
	public Date getModifieddate() {
		return this.modifieddate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((transactionid == null) ? 0 : transactionid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Transaction other = (Transaction) obj;
		if (transactionid == null) {
			if (other.transactionid != null) {
				return false;
			}
		} else if (!transactionid.equals(other.transactionid)) {
			return false;
		}
		return true;
	}

}
