package com.cosmetics.cosmeticspos.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of UserAccount.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Useraccount implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** userAccountId. */
	private Integer useraccountid;
	private int townshipId;

	/** profileName. */
	private String profilename;

	/** phone. */
	private String phone;

	/** address. */
	private String address;

	/** userName. */
	private String username;

	/** password. */
	private String password;

	/** date. */
	private Date date;

	/** userType. */
	private Object usertype;

	/** The set of Product. */
	private Set<Product> productSet;

	/** The set of Rating. */
	private Set<Rating> ratingSet;

	/** The set of Sale. */
	private Set<Sale> saleSet;

	/**
	 * Constructor.
	 */
	public Useraccount() {
		this.productSet = new HashSet<Product>();
		this.ratingSet = new HashSet<Rating>();
		this.saleSet = new HashSet<Sale>();
	}

	/**
	 * Set the userAccountId.
	 * 
	 * @param useraccountid
	 *            userAccountId
	 */
	public void setUseraccountid(Integer useraccountid) {
		this.useraccountid = useraccountid;
	}

	/**
	 * Get the userAccountId.
	 * 
	 * @return userAccountId
	 */
	public Integer getUseraccountid() {
		return this.useraccountid;
	}

	/**
	 * Set the profileName.
	 * 
	 * @param profilename
	 *            profileName
	 */
	public void setProfilename(String profilename) {
		this.profilename = profilename;
	}

	/**
	 * Get the profileName.
	 * 
	 * @return profileName
	 */
	public String getProfilename() {
		return this.profilename;
	}

	/**
	 * Set the phone.
	 * 
	 * @param phone
	 *            phone
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Get the phone.
	 * 
	 * @return phone
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * Set the address.
	 * 
	 * @param address
	 *            address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * Get the address.
	 * 
	 * @return address
	 */
	public String getAddress() {
		return this.address;
	}

	/**
	 * Set the userName.
	 * 
	 * @param username
	 *            userName
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * Get the userName.
	 * 
	 * @return userName
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the password.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the date.
	 * 
	 * @param date
	 *            date
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * Get the date.
	 * 
	 * @return date
	 */
	public Date getDate() {
		return this.date;
	}

	/**
	 * Set the userType.
	 * 
	 * @param usertype
	 *            userType
	 */
	public void setUsertype(Object usertype) {
		this.usertype = usertype;
	}

	/**
	 * Get the userType.
	 * 
	 * @return userType
	 */
	public Object getUsertype() {
		return this.usertype;
	}

	/**
	 * Set the set of the Product.
	 * 
	 * @param productSet
	 *            The set of Product
	 */
	public void setProductSet(Set<Product> productSet) {
		this.productSet = productSet;
	}

	/**
	 * Add the Product.
	 * 
	 * @param product
	 *            Product
	 */
	public void addProduct(Product product) {
		this.productSet.add(product);
	}

	/**
	 * Get the set of the Product.
	 * 
	 * @return The set of Product
	 */
	public Set<Product> getProductSet() {
		return this.productSet;
	}

	/**
	 * Set the set of the Rating.
	 * 
	 * @param ratingSet
	 *            The set of Rating
	 */
	public void setRatingSet(Set<Rating> ratingSet) {
		this.ratingSet = ratingSet;
	}

	/**
	 * Add the Rating.
	 * 
	 * @param rating
	 *            Rating
	 */
	public void addRating(Rating rating) {
		this.ratingSet.add(rating);
	}

	/**
	 * Get the set of the Rating.
	 * 
	 * @return The set of Rating
	 */
	public Set<Rating> getRatingSet() {
		return this.ratingSet;
	}

	/**
	 * Set the set of the Sale.
	 * 
	 * @param saleSet
	 *            The set of Sale
	 */
	public void setSaleSet(Set<Sale> saleSet) {
		this.saleSet = saleSet;
	}

	/**
	 * Add the Sale.
	 * 
	 * @param sale
	 *            Sale
	 */
	public void addSale(Sale sale) {
		this.saleSet.add(sale);
	}

	/**
	 * Get the set of the Sale.
	 * 
	 * @return The set of Sale
	 */
	public Set<Sale> getSaleSet() {
		return this.saleSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((useraccountid == null) ? 0 : useraccountid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Useraccount other = (Useraccount) obj;
		if (useraccountid == null) {
			if (other.useraccountid != null) {
				return false;
			}
		} else if (!useraccountid.equals(other.useraccountid)) {
			return false;
		}
		return true;
	}

}
